spring:
  datasource:
    name: software-order-test
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.37.20.199:3306/soft-test?serverTimezone=GMT%2B8
    username: remote
    password: issyu153

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
